version: 2
jobs:
  test:
    # working_directory: ~/sonar-simple-example
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - run: mvn test
      - run:
          command:
            if [ -z "$CIRCLE_PULL_REQUEST" ];
            then
              mvn sonar:sonar -Dsonar.projectKey=MollardMichael_sonar-simple-example -Dsonar.organization=mollardmichael-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN} -Dsonar.branch.name=${CIRCLE_BRANCH} -Dsonar.pullrequest.key=${CIRCLE_PULL_REQUEST##*/} -Dsonar.pullrequest.branch=${CIRCLE_BRANCH};
            else
              mvn sonar:sonar -Dsonar.projectKey=MollardMichael_sonar-simple-example -Dsonar.organization=mollardmichael-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN} -Dsonar.branch.name=${CIRCLE_BRANCH};
            fi

workflows:
  version: 2
  test:
    jobs:
      - test
